plugins {
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.86' apply false
}

ext.haikalatCoordinates = "com.github.KLjiana:haikalat:${haikalat_version}"

subprojects {
    apply plugin: "net.neoforged.moddev"

    neoForge {
        version = neo_version

        parchment {
            minecraftVersion = minecraft_version
            mappingsVersion = parchment_mappings
        }

        runs {
            client {
                client()
                systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            }

            server {
                server()
                programArgument '--nogui'
                setGameDirectory(file("server"))
                systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            }

            gameTestServer {
                type = "gameTestServer"
                systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            }

            data {
                data()

                programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
            }

            configureEach {
                systemProperty 'forge.logging.markers', 'REGISTRIES'
                logLevel = org.slf4j.event.Level.DEBUG

                jvmArgument "-XX:+IgnoreUnrecognizedVMOptions"
                jvmArgument "-XX:+AllowEnhancedClassRedefinition"
                jvmArgument "-XX:HotswapAgent=fatjar"

                if (isRunningInIdea()) {
                    systemProperty "terminal.jline", "true"
                }
            }
        }
    }

    repositories {
        mavenCentral()
        maven { url "https://maven.parchmentmc.org" }
        maven { url "https://maven.theillusivec4.top/" }
        maven { url "https://maven.shedaniel.me/" }
        maven { url "https://jitpack.io" }
        flatDir{ dirs 'libs' }
    }

    dependencies {
    }

    java {
        withSourcesJar()
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21

        toolchain.languageVersion = JavaLanguageVersion.of(21)
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.encoding = 'UTF-8'
        it.options.release = 21
    }

    def buildTime = new Date().format('yyyyMMdd-HHmmssSSS')
    tasks.named('jar') {
        archiveFileName.set("${mod_name}-${buildTime}.jar")
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

def isRunningInIdea() {
    return System.getProperty("idea.active") == "true"
}
